enum Actions {
  SERVERS_SET = "SERVERS_SET",
  CHANNELS_SET = "CHANNELS_SET",
  GROUPS_SET = "GROUPS_SET",
  MESSAGES_SET = "MESSAGES_SET",
  MEMBERS_SET = "MEMBERS_SET",
  USERS_SET = "USERS_SET",
  INITIAL_DATA_GATHERED = "INITIAL_DATA_GATHERED",
  SERVER_ADDED = "SERVER_ADDED",
  CHANNEL_ADDED = "CHANNEL_ADDED",
  GROUP_ADDED = "GROUP_ADDED",
  MESSAGES_ADDED = "MESSAGES_ADDED",
  SERVER_SELECTED = "SERVER_SELECTED",
  CHANNEL_SELECTED = "CHANNEL_SELECTED",
  OVERLAY_SET = "OVERLAY_SET",
  CHANNEL_MOVED = "CHANNEL_MOVED",
  DEVICE_LOADED = "DEVICE_LOADED"
}

export default Actions;